
package com.rainbow.tony.test.webservice.imp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "mySEIImpl", targetNamespace = "http://imp.sei.ldd.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MySEIImpl {
    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(
            localName = "sayHello",
            targetNamespace = "http://imp.sei.ldd.com/",
            className = "com.ldd.sei.imp.SayHello")
    @ResponseWrapper(
            localName = "sayHelloResponse",
            targetNamespace = "http://imp.sei.ldd.com/",
            className = "com.ldd.sei.imp.SayHelloResponse")
    @Action(
            input = "http://imp.sei.ldd.com/mySEIImpl/sayHelloRequest",
            output = "http://imp.sei.ldd.com/mySEIImpl/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
