
package com.rainbow.tony.test.webservice.imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "mySEIImplService", targetNamespace = "http://imp.sei.ldd.com/", wsdlLocation = "http://192.168.1.116:9090/web-service-sei/hellows?wsdl")
public class MySEIImplService
    extends Service
{

    private final static URL MYSEIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSEIIMPLSERVICE_EXCEPTION;
    private final static QName MYSEIIMPLSERVICE_QNAME = new QName("http://imp.sei.ldd.com/", "mySEIImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.116:9090/web-service-sei/hellows?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSEIIMPLSERVICE_WSDL_LOCATION = url;
        MYSEIIMPLSERVICE_EXCEPTION = e;
    }

    public MySEIImplService() {
        super(__getWsdlLocation(), MYSEIIMPLSERVICE_QNAME);
    }

    public MySEIImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSEIIMPLSERVICE_QNAME, features);
    }

    public MySEIImplService(URL wsdlLocation) {
        super(wsdlLocation, MYSEIIMPLSERVICE_QNAME);
    }

    public MySEIImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSEIIMPLSERVICE_QNAME, features);
    }

    public MySEIImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MySEIImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MySEIImpl
     */
    @WebEndpoint(name = "mySEIImplPort")
    public MySEIImpl getMySEIImplPort() {
        return super.getPort(new QName("http://imp.sei.ldd.com/", "mySEIImplPort"), MySEIImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MySEIImpl
     */
    @WebEndpoint(name = "mySEIImplPort")
    public MySEIImpl getMySEIImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imp.sei.ldd.com/", "mySEIImplPort"), MySEIImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSEIIMPLSERVICE_EXCEPTION!= null) {
            throw MYSEIIMPLSERVICE_EXCEPTION;
        }
        return MYSEIIMPLSERVICE_WSDL_LOCATION;
    }

}
