spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
server:
  port: 8088
sharding:
  jdbc:
    data-sources:
      ds_master:
        type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/master?characterEncoding=utf-8&useSSL=false
            username: root
            password: root
      ds_slave:
        type: com.zxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.jdbc.Driver
          jdbc-url: jdbc:mysql://localhost:3306/slave?characterEncoding=utf8&useSSL=false
          username: root
          password: root
        master-slave-rule:
          name: ds_ms
          master-data-source-name: ds_master
          slave-data-source-names: ds_slave
          load-balance-algorithm-type: round-robin

